### ISSUE TITLE
Gameobject Flicker Issue (Material)

### ISSUE THREAD

**Issue by mp0302** [pastasfuture/com.hauntedpsx.render-pipelines.psx#36] opened 2023-05-15 04:55 UTC
So I have been trying out this shader for a while and came across some issue. When I changed the material to the corresponding shader, it has this kind of **flickering**, where the trees pop in and out, although the trees are present because I can collide with their colliders except they're not being rendered, they just **flicker** everywhere, it also happens with objects that I just changed the material to PSX/Lit,. Here's the video and pictures for additional information.

https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx/assets/104110725/b1dc7043-47e6-4109-84c7-db081494f7e1
https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx/assets/104110725/1944ef2a-04a0-4c12-9772-c6addcae3d74

![image_2023-05-15_125328837](https://github.com/pastasfuture/com.hauntedpsx.render-pipelines.psx/assets/104110725/8a914a2b-31d2-4624-b6da-c8f01e63a03c)

any fix to this? thank you!

**Comment by pastasfuture** [comment] 2023-05-15 15:21
Interesting! I’ve never seen this specific bug before - but I just noticed in your material screenshot you have gpu instancing on - can you try turning that off to see if the bug goes away? I think gpu instancing may be bugged. If we can confirm the issue is gpu instancing I can then look at fixing that

**Comment by gd-b** [comment] 2023-05-16 15:07
it did go away! the objects stop flickering now, thank you very much and will be looking forward for the fix! have a good one!

**Comment by pastasfuture** [comment] 2023-10-01 01:53
Fixed on master as of e779c1c2af4a4a1fc2b98807063cc547ea49877d

**Closed by pastasfuture** 2023-10-01 01:53 UTC
